name: tetbiq
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.0
  bottom_navy_bar: ^6.0.0
  cloud_firestore: ^4.13.3
  eva_icons_flutter: ^3.1.0
  file_picker: ^6.1.1
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  firebase_storage: ^11.5.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  ionicons: ^0.2.2
  linear_progress_bar: ^1.1.0
  modal_bottom_sheet: ^2.1.2
  permission_handler: ^11.1.0
  persistent_bottom_nav_bar: ^5.0.2
  provider: ^6.1.1
  sign_in_button: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  assets: 
    - assets/images/